### ISSUE TITLE
用Gmail邮箱接收信息 报错

### ISSUE THREAD

**Issue by cliya** [lx1169732264/zdm#3]
```
```com.sun.mail.smtp.SMTPSendFailedException: 530-5.7.0 Must issue a STARTTLS command first. For more information, go to
530-5.7.0  https://support.google.com/a/answer/3221692 and review RFC 3207
530 5.7.0 specifications. d9443c01a7336-1f632416d90sm95628645ad.285 - gsmtp

	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2358)
	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1823)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1300)
	at javax.mail.Transport.send0(Transport.java:255)
	at javax.mail.Transport.send(Transport.java:124)
	at lx.ZdmCrawler.sendEmail(ZdmCrawler.java:121)
	at lx.ZdmCrawler.main(ZdmCrawler.java:97)`
```
用Gmail邮箱接收信息 报错
确认密码正确

**Comment by shuosiw** [comment]
qq 邮箱好像也不行了，强制要求走 smtps，也就是 465 端口或者 587，估计是针对新创建的授权码做了限制，之前已经创建的还是允许普通 stmp 非加密

```
javax.mail.AuthenticationFailedException: 530 Login fail. A secure connection is requiered(such as ssl). More information at http://service.mail.qq.com/cgi-bin/help?id=28
	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at lx.ZdmCrawler.sendEmail(ZdmCrawler.java:121)
	at lx.ZdmCrawler.main(ZdmCrawler.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by cliya** [comment]
山东尚家具欢迎您www.sjiaju.com

**Comment by lx1169732264** [comment]
适配smtps的pr已合并进主分支, 这个issue就关闭了
